version: "3.7"

services:
    document-manager-app:
        platform: "linux/amd64"
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "5555:443"
            - "8888:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    document-manager-db:
        platform: "linux/amd64"
        image: mysql:5.7.34
        restart: unless-stopped
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
            - "3333:3333"
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge